const DEPARTMENTS = [
  "Assembly", 
  "5 Axis",
  "ADM",
  "SR",
  "AMB CNC",
  "AMB Core Pin",
  "AMB GUN Drilling",
  "AMB Quality",
  "AMB Rough Machining",
  "AMB Round Parts",
  "AMB Water Cooling",
  "Assembly",
  "CNC",
  "Design NPD",
  "Design RPD",
  "DTI Gundrilling",
  "EDM",
  "ERP",
  "Electrode",
  "Flow",
  "Housing",
  "Internal Nitriding",
  "Lean Assembly",
  "Lean CNC",
  "Lean Design",
  "Lean EDM",
  "Lean Polishing",
  "Lean Process Input",
  "Lean Wirecut",
  "Maintenance",
  "Marketing",
  "Milling",
  "Others",
  "PDC",
  "Plant-ii Mouldbase",
  "Polishing",
  "Process Input",
  "Purchase",
  "QAD CAD",
  "Quality",
  "Rough Machining",
  "SPM CNC",
  "SPM Core Pin",
  "SPM Quality",
  "SPM Rough Machining",
  "SPM Round Parts",
  "SPM Water Cooling",
  "Service Cell",
  "WIRECUT",
  "JIT",
  "CNC",
  "Design",
  "Finance",
  "HR",
  "IT",
  "Maintenance",
  "Marketing",
  "PPC",
  "Production",
  "Purchase",
  "QA",
  "QC",
  "Quality",
  "R&D",
  "Sales",
  "Stores",
  "TPM",
];

export default DEPARTMENTS;